/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dibujos;

import com.mycompany.dibujos.Parametros.Parametros;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;

/**
 *
 * @author Jonna
 */
public class VentanaParametros extends javax.swing.JInternalFrame {

    private static PanelPaint panelPaint = new PanelPaint();
    
    public static List<Parametros> parametros = new ArrayList<>();

    /**
     * Creates new form VentanaParametros
     */
    public VentanaParametros() {

        initComponents();
        this.setIconifiable(true);
        this.setIgnoreRepaint(true);
        this.setVisible(true);
        this.setClosable(true);
        this.setResizable(true);
        this.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
    }

    public List<Parametros> mostrar(List<Parametros> parametrosRecibidos) {

        return parametrosRecibidos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbFiguras = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btDibujar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtAncho = new javax.swing.JTextField();
        txtAlto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbColor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PARAMETROS DE LA FIGURA");

        cbFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estrella", "Círculo", "Cuadrado", "Rectángulo", "Triángulo" }));
        cbFiguras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFigurasItemStateChanged(evt);
            }
        });
        cbFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFigurasActionPerformed(evt);
            }
        });

        jLabel2.setText("Figura");

        btDibujar.setText("Dibujar");
        btDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDibujarActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar todo");

        txtAncho.setEnabled(false);

        txtAlto.setEnabled(false);
        txtAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltoActionPerformed(evt);
            }
        });

        jLabel3.setText("Ancho");

        jLabel4.setText("Alto");

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "azul", "rojo", "verde", "amarillo" }));
        cbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColorActionPerformed(evt);
            }
        });

        jLabel5.setText("Color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btDibujar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAncho, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(txtAlto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(102, 102, 102)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDibujar)
                    .addComponent(jButton2))
                .addGap(143, 143, 143))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFigurasActionPerformed
        //var figura = txt

    }//GEN-LAST:event_cbFigurasActionPerformed

    private void txtAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltoActionPerformed

    private void cbFigurasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFigurasItemStateChanged
        // TODO add your handling code here:
        String figuraSelec = cbFiguras.getSelectedItem().toString();
        switch (figuraSelec) {
            case "Estrella":
                txtAncho.setEnabled(true);
                txtAlto.setEnabled(false);
                txtAlto.setText("");
                break;
            case "Círculo":
                txtAncho.setEnabled(true);
                txtAlto.setEnabled(false);
                txtAlto.setText("");
                break;
            case "Cuadrado":
                txtAncho.setEnabled(true);
                txtAlto.setEnabled(false);
                txtAlto.setText("");
                break;
            case "Rectángulo":
                txtAncho.setEnabled(true);
                txtAlto.setEnabled(true);
                break;
            case "Triángulo":
                txtAncho.setEnabled(true);
                txtAlto.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_cbFigurasItemStateChanged

    private void btDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDibujarActionPerformed
        // TODO add your handling code here:
        
        var datos = new String[4];

        if (txtAlto.isEnabled()) {
            datos[0] = txtAlto.getText();
        } else {
            datos[0] = "0";
        }

        datos[1] = txtAncho.getText();
        datos[2] = cbFiguras.getSelectedItem().toString();
        datos[3] = this.cbColor.getSelectedItem().toString();
        panelPaint.recibeDatos(datos);
        
        VentanaDibujar ventanaDibujar = new VentanaDibujar();
        
        ventanaDibujar.setVisible(true);

    }//GEN-LAST:event_btDibujarActionPerformed

    private void cbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDibujar;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JComboBox<String> cbFiguras;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    // End of variables declaration//GEN-END:variables
}
